REGIONS: dict[str, list[str]] = {
    "Andijon": [
        "Andijon shahri",
        "Asaka",
        "Baliqchi",
        "Bo'z",
        "Buloqboshi",
        "Izboskan",
        "Jalaquduq",
        "Marhamat",
        "Oltinko'l",
        "Paxtaobod",
        "Qo'rg'ontepa",
        "Shahrixon",
        "Ulug'nor",
        "Xo'jaobod",
    ],
    "Buxoro": [
        "Buxoro shahri",
        "Buxoro",
        "G'ijduvon",
        "Jondor",
        "Kogon",
        "Olot",
        "Peshku",
        "Qorako'l",
        "Qorovulbozor",
        "Romitan",
        "Shofirkon",
        "Vobkent",
    ],
    "Farg'ona": [
        "Farg'ona shahri",
        "Beshariq",
        "Bog'dod",
        "Buvayda",
        "Dang'ara",
        "Farg'ona",
        "Furqat",
        "Oltiariq",
        "Qo'qon",
        "Quva",
        "Quvasoy",
        "Rishton",
        "So'x",
        "Toshloq",
        "Uchko'prik",
        "Yozyovon",
    ],
    "Jizzax": [
        "Jizzax shahri",
        "Arnasoy",
        "Baxmal",
        "Do'stlik",
        "Forish",
        "G'allaorol",
        "Jizzax",
        "Mirzacho'l",
        "Paxtakor",
        "Yangiobod",
        "Zafarobod",
        "Zarbdor",
        "Zomin",
    ],
    "Namangan": [
        "Namangan shahri",
        "Chortoq",
        "Chust",
        "Kosonsoy",
        "Mingbuloq",
        "Namangan",
        "Norin",
        "Pop",
        "To'raqo'rg'on",
        "Uchqo'rg'on",
        "Uychi",
        "Yangiqo'rg'on",
    ],
    "Navoiy": [
        "Navoiy shahri",
        "Karmana",
        "Konimex",
        "Navbahor",
        "Nurota",
        "Qiziltepa",
        "Tomdi",
        "Uchquduq",
        "Xatirchi",
        "Zarafshon",
    ],
    "Qashqadaryo": [
        "Qarshi shahri",
        "Chiroqchi",
        "Dehqonobod",
        "G'uzor",
        "Kasbi",
        "Kitob",
        "Koson",
        "Mirishkor",
        "Muborak",
        "Nishon",
        "Qamashi",
        "Qarshi",
        "Shahrisabz",
        "Yakkabog'",
    ],
    "Qoraqalpog'iston Respublikasi": [
        "Nukus shahri",
        "Amudaryo",
        "Beruniy",
        "Bo'zatov",
        "Chimboy",
        "Ellikqal'a",
        "Kegeyli",
        "Mo'ynoq",
        "Nukus",
        "Qanliko'l",
        "Qo'ng'irot",
        "Qorao'zak",
        "Shumanay",
        "Taxtako'pir",
        "To'rtko'l",
        "Xo'jayli",
    ],
    "Samarqand": [
        "Samarqand shahri",
        "Bulung'ur",
        "Ishtixon",
        "Jomboy",
        "Kattaqo'rg'on",
        "Narpay",
        "Nurobod",
        "Oqdaryo",
        "Pastdarg'om",
        "Paxtachi",
        "Payariq",
        "Qo'shrabot",
        "Samarqand",
        "Toyloq",
        "Urgut",
    ],
    "Sirdaryo": [
        "Guliston shahri",
        "Boyovut",
        "Guliston",
        "Mirzaobod",
        "Oqoltin",
        "Sardoba",
        "Sayxunobod",
        "Shirin",
        "Sirdaryo",
        "Xovos",
        "Yangiyer",
    ],
    "Surxondaryo": [
        "Termiz shahri",
        "Angor",
        "Bandixon",
        "Boysun",
        "Denov",
        "Jarqo'rg'on",
        "Muzrabot",
        "Oltinsoy",
        "Qiziriq",
        "Qumqo'rg'on",
        "Sariosiyo",
        "Sherobod",
        "Sho'rchi",
        "Termiz",
        "Uzun",
    ],
    "Toshkent": [
        "Nurafshon shahri",
        "Bekobod",
        "Bo'ka",
        "Bo'stonliq",
        "Chinoz",
        "Ohangaron",
        "Oqqo'rg'on",
        "Parkent",
        "Piskent",
        "Quyi Chirchiq",
        "Toshkent",
        "Yangiyo'l",
        "Yuqori Chirchiq",
        "Zangiota",
    ],
    "Toshkent shahri": [
        "Bektemir",
        "Chilonzor",
        "Mirobod",
        "Mirzo Ulug'bek",
        "Olmazor",
        "Sergeli",
        "Shayxontohur",
        "Uchtepa",
        "Yakkasaroy",
        "Yashnobod",
        "Yunusobod",
        "Yangihayot",
    ],
    "Xorazm": [
        "Urganch shahri",
        "Bog'ot",
        "Gurlan",
        "Hazorasp",
        "Khiva",
        "Qo'shko'pir",
        "Shovot",
        "Urganch",
        "Xonqa",
        "Yangiariq",
        "Yangibozor",
    ],
}

REFERRAL_REWARD = 5
MIN_REFERRALS_FOR_TEST = 3
LANGUAGES = {
    "uz_latin": "O'zbekcha",
    "uz_cyrillic": "Ўзбекча",
    "ru": "Русский",
}
MENU_KEYS = [
    "cabinet",
    "invite",
    "test",
    "results",
    "rules",
    "books",
    "question",
]
